######################################################
# ---- (01.)SERVER-PORT-CONFIGURATION ----
######################################################
server:
  port: 9103

######################################################
# ---- (02.)ACTUATOR-CONFIGURATION ----
######################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"

######################################################
# ---- (03.)EUREKA-CONFIGURATION ----
######################################################
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:9102/eureka/"

######################################################
# ---- (04.)LOGGING-CONFIGURATION ----
######################################################
logging:
  config: "classpath:log4j2-spring.xml"

######################################################
# ---- (05.)SPRING-SECURITY-CONFIGURATION ----
######################################################
spring:
  security:
    user:
      name: "utilisateur"
      password: "mdp"

######################################################
# ---- (06.)MY CONFIGURATION ----
######################################################
ma-config:
  parametreDExemple: 40
  
