######################################################
# ---- (01.)SERVER-PORT-CONFIGURATION ----
######################################################
server:
  port: 9103

######################################################
# ---- (02.)ACTUATOR-CONFIGURATION ----
######################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"

######################################################
# ---- (03.)EUREKA-CONFIGURATION ----
######################################################
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:9102/eureka/"

######################################################
# ---- (04.)SPRING-SECURITY-CONFIGURATION ----
######################################################
spring:
  security:
    user:
      name: "utilisateur"
      password: "mdp"

######################################################
# ---- (05.)HYSTRIX-CONFIGURATION ----
######################################################
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

######################################################
# ---- (06.)ZUUL-CONFIGURATION ----
######################################################
zuul:
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 5000
  #ignoredServices: '*'
  routes:
    application:
      #path: /application/**
      #serviceId: application
      sensitive-headers: Cookie,Set-Cookie,Authorization

######################################################
# ---- (07.)RIBBON-CONFIGURATION ----
######################################################
ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000

######################################################
# ---- (08.)LOGGING-CONFIGURATION ----
######################################################
logging:
  config: "classpath:log4j2-spring.xml"

######################################################
# ---- (09.)MY CONFIGURATION ----
######################################################
ma-config:
  parametreDExemple: 40
  
